version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Installing dependencies...
      - pip install -r requirements.txt
  build:
    commands:
      - echo Running application...
      - python app.py
      - echo $CODEBUILD_SRC_DIR
      - yum install curl
